general:
  isOn: true

slowmode:
  # time in seconds
  time: 20
  message: You send the message to quickly!

auto:
  autoOn: false
  # the amount of messages needed to turn auto on
  messages: 10

doNotChange:
  # DO NOT CHANGE!!!
  cfgVersion: 1.1