name: ChatCooldown
main: matthbo.plugin.chatcooldown.ChatCooldown
version: 0.1.1
commands:
    ccooldown:
        description: ChatCooldown Commands
        usage: /<command> enable | /<command> disable